Quick program for looking at EDGAR filing attributes

In [21]:
import pandas as pd
import string as str

In [22]:
df = pd.read_csv('us_gaap_attributes.csv', index_col=0)

In [23]:
df.head()

                                           attribute
0        AcceleratedShareRepurchaseProgramAdjustment
1  AcceleratedShareRepurchasesFinalPricePaidPerShare
2  AcceleratedShareRepurchasesSettlementPaymentOr...
3  AccountsAndFinancingReceivableAllowanceForCred...
4                      AccountsAndNotesReceivableNet

In [24]:
att_df = df[df.attribute.str.match('Accounts')]

In [25]:
att_df.head()

                                           attribute
3  AccountsAndFinancingReceivableAllowanceForCred...
4                      AccountsAndNotesReceivableNet
5              AccountsAndOtherReceivablesNetCurrent
6          AccountsNotesAndLoansReceivableNetCurrent
7                                    AccountsPayable

In [26]:
att_df.sort_values(by="attribute", key=lambda x: x.str.len())

                                            attribute
7                                     AccountsPayable
26                              AccountsReceivableNet
30                             AccountsReceivableSale
15                             AccountsPayableCurrent
16                        AccountsPayableOtherCurrent
19                        AccountsPayableTradeCurrent
27                       AccountsReceivableNetCurrent
4                       AccountsAndNotesReceivableNet
24                     AccountsReceivableGrossCurrent
28                    AccountsReceivableNetNoncurrent
29                   AccountsReceivableRelatedParties
25                  AccountsReceivableGrossNoncurrent
8                AccountsPayableAndAccruedLiabilities
18               AccountsPayableRelatedPartiesCurrent
5               AccountsAndOtherReceivablesNetCurrent
17           AccountsPayableOtherCurrentAndNoncurrent
6           AccountsNotesAndLoansReceivableNetCurrent
13          AccountsPayableAndOtherAccruedLiabilities
9         AccountsPayableAndAccruedLiabilitiesCurrent
12     AccountsPayableAndAccruedLiabilitiesNoncurrent
14   AccountsPayableAndOtherAccruedLiabilitiesCurrent
3   AccountsAndFinancingReceivableAllowanceForCred...
21  AccountsReceivableBilledForLongTermContractsOr...
11  AccountsPayableAndAccruedLiabilitiesFairValueD...
10  AccountsPayableAndAccruedLiabilitiesCurrentAnd...
22  AccountsReceivableChangeInMethodCreditLossExpe...
20  AccountsReceivableAllowanceForCreditLossExclud...
23  AccountsReceivableExcludingAccruedInterestAfte...